<?php

return [
    'quan_ly_giao_vien' => [
        'ten' => 'Tên giáo viên',
        'ten_co_so' => 'Tên cơ sở',
        'gioi_tinh' => 'Giới tính',
        'dan_toc_it_nguoi' => 'Dân tộc <br> thiểu số',
        'mon_chung' => 'Môn chung',
        'chuc_danh' => 'Chức danh',
        'loai_hop_dong' => 'Loại hợp đồng',
        'danh_hieu' => 'Danh hiệu',
        'trinh_do_ngoai_ngu' => 'Ngoại ngữ',
        'trinh_do_ky_nang_nghe' => 'Kỹ năng',
        'trinh_do' => 'Trình độ',
        'nganh_nghe' => 'Ngành nghề',
    ],
    'so_lieu_can_bo_quan_ly' => [
        'ten_co_so' => 'Tên đơn vị',
        'loai_hinh' => 'Loại hình/Cấp quản lý',
        'tong_so' => 'Tổng số',
    ],
    'so_lieu_can_bo_quan_ly_show' => [
        'nam' => 'Năm',
        'dot' => 'Đợt',
        'tong_so_quan_ly' => 'Tổng số',
        'so_cb_quan_ly_nu' => 'Nữ',
        'so_dan_toc' => 'Dân tộc thiểu số',
        'so_cb_giang_day' => 'Tham gia giảng dạy',
        'so_cb_da_boi_duong' => 'Đã qua bồi dưỡng',
        'so_danh_hieu' => 'Danh hiệu nhà giáo',
        'so_hieu_truong' => 'Hiệu trưởng',
        'so_hieu_pho' => 'Hiệu phó',
        'so_truong_khoa' => 'Trưởng phòng khoa',
        'so_pho_phong' => 'Phó phòng khoa',
        'so_to_truong' => 'Tổ trưởng chuyên môn',
        'so_trinh_do_tien_sy' => 'Tiến sỹ',
        'so_trinh_do_thac_sy' => 'Thạc sỹ',
        'so_trinh_do_dai_hoc' => 'Đại học',
        'so_trinh_do_cao_dang' => 'Cao đẳng',
        'so_trinh_do_trung_cap' => 'Trung cấp',
        'so_trinh_do_khac' => 'Trình độ khác',
    ],
];
